# rm( grupo01MaskSample )
# rm( grupo02MaskSample )
# rm( grupo03MaskSample )
# rm( grupo04MaskSample )
# rm( grupo05MaskSample )
# rm( grupo06MaskSample )
# rm( grupo00MaskSample )

# if( file.exists( "../bigmatrices/grupo01MaskSample.desc" ) ) file.remove( "../bigmatrices/grupo01MaskSample.desc" )
# if( file.exists( "../bigmatrices/grupo02MaskSample.desc" ) ) file.remove( "../bigmatrices/grupo02MaskSample.desc" )
# if( file.exists( "../bigmatrices/grupo03MaskSample.desc" ) ) file.remove( "../bigmatrices/grupo03MaskSample.desc" )
# if( file.exists( "../bigmatrices/grupo04MaskSample.desc" ) ) file.remove( "../bigmatrices/grupo04MaskSample.desc" )
# if( file.exists( "../bigmatrices/grupo05MaskSample.desc" ) ) file.remove( "../bigmatrices/grupo05MaskSample.desc" )
# if( file.exists( "../bigmatrices/grupo06MaskSample.desc" ) ) file.remove( "../bigmatrices/grupo06MaskSample.desc" )
# if( file.exists( "../bigmatrices/grupo00MaskSample.desc" ) ) file.remove( "../bigmatrices/grupo00MaskSample.desc" )

# if( file.exists( "../bigmatrices/grupo01MaskSample.bin" )  ) file.remove( "../bigmatrices/grupo01MaskSample.bin" )
# if( file.exists( "../bigmatrices/grupo02MaskSample.bin" )  ) file.remove( "../bigmatrices/grupo02MaskSample.bin" )
# if( file.exists( "../bigmatrices/grupo03MaskSample.bin" )  ) file.remove( "../bigmatrices/grupo03MaskSample.bin" )
# if( file.exists( "../bigmatrices/grupo04MaskSample.bin" )  ) file.remove( "../bigmatrices/grupo04MaskSample.bin" )
# if( file.exists( "../bigmatrices/grupo05MaskSample.bin" )  ) file.remove( "../bigmatrices/grupo05MaskSample.bin" )
# if( file.exists( "../bigmatrices/grupo06MaskSample.bin" )  ) file.remove( "../bigmatrices/grupo06MaskSample.bin" )
# if( file.exists( "../bigmatrices/grupo00MaskSample.bin" )  ) file.remove( "../bigmatrices/grupo00MaskSample.bin" )

  ### revisar grupo00 desde mascara y remuestreo
  print( system.time( grupo01MaskSample <- bigmemory::read.big.matrix( "../CapasFAU23_5/grupo01MaskSample/grupo01bm.csv" , header = T , sep = "," , type="double" , backingpath="../bigmatrices" , backingfile="grupo01bm.bin" , descriptorfile="grupo01bm.desc" , shared = T ) ) )
  print( system.time( grupo02MaskSample <- bigmemory::read.big.matrix( "../CapasFAU23_5/grupo02MaskSample/grupo02bm.csv" , header = T , sep = "," , type="double" , backingpath="../bigmatrices" , backingfile="grupo02bm.bin" , descriptorfile="grupo02bm.desc" , shared = T ) ) )
  print( system.time( grupo03MaskSample <- bigmemory::read.big.matrix( "../CapasFAU23_5/grupo03MaskSample/grupo03bm.csv" , header = T , sep = "," , type="double" , backingpath="../bigmatrices" , backingfile="grupo03bm.bin" , descriptorfile="grupo03bm.desc" , shared = T ) ) )
  print( system.time( grupo04MaskSample <- bigmemory::read.big.matrix( "../CapasFAU23_5/grupo04MaskSample/grupo04bm.csv" , header = T , sep = "," , type="double" , backingpath="../bigmatrices" , backingfile="grupo04bm.bin" , descriptorfile="grupo04bm.desc" , shared = T ) ) )
  print( system.time( grupo05MaskSample <- bigmemory::read.big.matrix( "../CapasFAU23_5/grupo05MaskSample/grupo05bm.csv" , header = T , sep = "," , type="double" , backingpath="../bigmatrices" , backingfile="grupo05bm.bin" , descriptorfile="grupo05bm.desc" , shared = T ) ) )
  print( system.time( grupo06MaskSample <- bigmemory::read.big.matrix( "../CapasFAU23_5/grupo06MaskSample/grupo06bm.csv" , header = T , sep = "," , type="double" , backingpath="../bigmatrices" , backingfile="grupo06bm.bin" , descriptorfile="grupo06bm.desc" , shared = T ) ) )
  print( system.time( grupo00MaskSample <- bigmemory::read.big.matrix( "../CapasFAU23_5/grupo00MaskSample/grupo00bm.csv" , header = T , sep = "," , type="double" , backingpath="../bigmatrices" , backingfile="grupo00bm.bin" , descriptorfile="grupo00bm.desc" , shared = T ) ) )
