  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_TRI_px25.tif           | grep -i --color 'file\|size is'   | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_slope_px25.tif         | grep -i --color 'file\|size is'   | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_asp_x_px25.tif         | grep -i --color 'file\|size is'   | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_DEM_px25.tif           | grep -i --color 'file\|size is'   | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_asp_y_px25.tif         | grep -i --color 'file\|size is'   | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_carbono_2013_px25.tif  | grep -i --color 'file\|size is'   | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../petra_biotopos/previos/Clas_geo_clip.tif                                | grep -i --color 'file\|size is'   | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  echo
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_TRI_px25.tif           | grep -i --color 'file\|origin ='  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_slope_px25.tif         | grep -i --color 'file\|origin ='  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_asp_x_px25.tif         | grep -i --color 'file\|origin ='  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_DEM_px25.tif           | grep -i --color 'file\|origin ='  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_asp_y_px25.tif         | grep -i --color 'file\|origin ='  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_carbono_2013_px25.tif  | grep -i --color 'file\|origin ='  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../petra_biotopos/previos/Clas_geo_clip.tif                                | grep -i --color 'file\|origin ='  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  echo
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_TRI_px25.tif           | grep -i --color 'file\|pixel size'  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_slope_px25.tif         | grep -i --color 'file\|pixel size'  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_asp_x_px25.tif         | grep -i --color 'file\|pixel size'  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_DEM_px25.tif           | grep -i --color 'file\|pixel size'  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_asp_y_px25.tif         | grep -i --color 'file\|pixel size'  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../DriveBiotopos/Daniel_Zamorano/Pixel25Norm/Transf_carbono_2013_px25.tif  | grep -i --color 'file\|pixel size'  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
  gdalinfo ../../petra_biotopos/previos/Clas_geo_clip.tif                                | grep -i --color 'file\|pixel size'  | sed -r 'N;s/\n/:/'  | gawk 'BEGIN{FS=OFS=":"} {print $3,$1,$2}'
