# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/Aspect_remuestreado_grupo00_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/Aspect_remuestreado_grupo00_mask.grd" < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/DEM_remuestreado_grupo00_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/DEM_remuestreado_grupo00_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/NDMI_remuestreado_grupo00_mask.tif"   "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/NDMI_remuestreado_grupo00_mask.grd"   < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/Slope_remuestreado_grupo00_mask.tif"  "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/Slope_remuestreado_grupo00_mask.grd"  < FuncionConvertirRasters.R
 #R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/TRI_remuestreado_grupo00_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/TRI_remuestreado_grupo00_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/TWI_remuestreado_grupo00_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/TWI_remuestreado_grupo00_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/Aspect_remuestreado_grupo01_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/Aspect_remuestreado_grupo01_mask.grd" < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/DEM_remuestreado_grupo01_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/DEM_remuestreado_grupo01_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/NDMI_remuestreado_grupo01_mask.tif"   "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/NDMI_remuestreado_grupo01_mask.grd"   < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/Slope_remuestreado_grupo01_mask.tif"  "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/Slope_remuestreado_grupo01_mask.grd"  < FuncionConvertirRasters.R
 #R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/TRI_remuestreado_grupo01_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/TRI_remuestreado_grupo01_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/TWI_remuestreado_grupo01_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/TWI_remuestreado_grupo01_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/Aspect_remuestreado_grupo02_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/Aspect_remuestreado_grupo02_mask.grd" < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/DEM_remuestreado_grupo02_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/DEM_remuestreado_grupo02_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/NDMI_remuestreado_grupo02_mask.tif"   "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/NDMI_remuestreado_grupo02_mask.grd"   < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/Slope_remuestreado_grupo02_mask.tif"  "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/Slope_remuestreado_grupo02_mask.grd"  < FuncionConvertirRasters.R
 #R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/TRI_remuestreado_grupo02_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/TRI_remuestreado_grupo02_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/TWI_remuestreado_grupo02_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/TWI_remuestreado_grupo02_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/Aspect_remuestreado_grupo03_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/Aspect_remuestreado_grupo03_mask.grd" < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/DEM_remuestreado_grupo03_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/DEM_remuestreado_grupo03_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/NDMI_remuestreado_grupo03_mask.tif"   "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/NDMI_remuestreado_grupo03_mask.grd"   < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/Slope_remuestreado_grupo03_mask.tif"  "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/Slope_remuestreado_grupo03_mask.grd"  < FuncionConvertirRasters.R
 #R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/TRI_remuestreado_grupo03_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/TRI_remuestreado_grupo03_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/TWI_remuestreado_grupo03_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/TWI_remuestreado_grupo03_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/Aspect_remuestreado_grupo04_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/Aspect_remuestreado_grupo04_mask.grd" < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/DEM_remuestreado_grupo04_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/DEM_remuestreado_grupo04_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/NDMI_remuestreado_grupo04_mask.tif"   "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/NDMI_remuestreado_grupo04_mask.grd"   < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/Slope_remuestreado_grupo04_mask.tif"  "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/Slope_remuestreado_grupo04_mask.grd"  < FuncionConvertirRasters.R
 #R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/TRI_remuestreado_grupo04_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/TRI_remuestreado_grupo04_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/TWI_remuestreado_grupo04_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/TWI_remuestreado_grupo04_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/Aspect_remuestreado_grupo05_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/Aspect_remuestreado_grupo05_mask.grd" < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/DEM_remuestreado_grupo05_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/DEM_remuestreado_grupo05_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/NDMI_remuestreado_grupo05_mask.tif"   "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/NDMI_remuestreado_grupo05_mask.grd"   < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/Slope_remuestreado_grupo05_mask.tif"  "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/Slope_remuestreado_grupo05_mask.grd"  < FuncionConvertirRasters.R
 #R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/TRI_remuestreado_grupo05_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/TRI_remuestreado_grupo05_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/TWI_remuestreado_grupo05_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/TWI_remuestreado_grupo05_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/Aspect_remuestreado_grupo06_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/Aspect_remuestreado_grupo06_mask.grd" < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/DEM_remuestreado_grupo06_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/DEM_remuestreado_grupo06_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/NDMI_remuestreado_grupo06_mask.tif"   "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/NDMI_remuestreado_grupo06_mask.grd"   < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/Slope_remuestreado_grupo06_mask.tif"  "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/Slope_remuestreado_grupo06_mask.grd"  < FuncionConvertirRasters.R
 #R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/TRI_remuestreado_grupo06_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/TRI_remuestreado_grupo06_mask.grd"    < FuncionConvertirRasters.R
# R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/TWI_remuestreado_grupo06_mask.tif"    "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/TWI_remuestreado_grupo06_mask.grd"    < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/Asp__x_remuestreado_grupo00_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/Asp__x_remuestreado_grupo00_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/Asp__y_remuestreado_grupo00_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo00MaskSample/Asp__y_remuestreado_grupo00_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/Asp__x_remuestreado_grupo01_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/Asp__x_remuestreado_grupo01_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/Asp__y_remuestreado_grupo01_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo01MaskSample/Asp__y_remuestreado_grupo01_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/Asp__x_remuestreado_grupo02_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/Asp__x_remuestreado_grupo02_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/Asp__y_remuestreado_grupo02_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo02MaskSample/Asp__y_remuestreado_grupo02_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/Asp__x_remuestreado_grupo03_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/Asp__x_remuestreado_grupo03_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/Asp__y_remuestreado_grupo03_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo03MaskSample/Asp__y_remuestreado_grupo03_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/Asp__x_remuestreado_grupo04_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/Asp__x_remuestreado_grupo04_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/Asp__y_remuestreado_grupo04_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo04MaskSample/Asp__y_remuestreado_grupo04_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/Asp__x_remuestreado_grupo05_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/Asp__x_remuestreado_grupo05_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/Asp__y_remuestreado_grupo05_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo05MaskSample/Asp__y_remuestreado_grupo05_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/Asp__x_remuestreado_grupo06_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/Asp__x_remuestreado_grupo06_mask.grd" < FuncionConvertirRasters.R
  R --slave --args "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/Asp__y_remuestreado_grupo06_mask.tif" "../../DriveBiotopos/Matias_Rebolledo/Raster/CapasFAU23_5/grupo06MaskSample/Asp__y_remuestreado_grupo06_mask.grd" < FuncionConvertirRasters.R
