# ## Renombrar archivos gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ dNDVI .gdalinfo"             ../../Daniel_Zamorano/Rasters/Transf__dNDVI_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ SOS .gdalinfo"               ../../Daniel_Zamorano/Rasters/Transf__SOS_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ AMP .gdalinfo"               ../../Daniel_Zamorano/Rasters/Transf__AMP_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ bio_12 .gdalinfo"            ../../Daniel_Zamorano/Rasters/Transf__bio_12_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ Dist_agua .gdalinfo"         ../../Daniel_Zamorano/Rasters/Transf__Dist_agua_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ LOS .gdalinfo"               ../../Daniel_Zamorano/Rasters/Transf__LOS_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ Carbono_2013 .gdalinfo"      ../../Daniel_Zamorano/Rasters/Transf__Carbono_2013_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ asp_y .gdalinfo"             ../../Daniel_Zamorano/Rasters/Transf__asp_y_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ EOS .gdalinfo"               ../../Daniel_Zamorano/Rasters/Transf__EOS_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ slope .gdalinfo"             ../../Daniel_Zamorano/Rasters/Transf__slope_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ dem30_final .gdalinfo"       ../../Daniel_Zamorano/Rasters/Transf__dem30_final_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ bio_15 .gdalinfo"            ../../Daniel_Zamorano/Rasters/Transf__bio_15_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ asp_x .gdalinfo"             ../../Daniel_Zamorano/Rasters/Transf__asp_x_.gdalinfo
# mv "../../Daniel_Zamorano/Rasters/Transf_ promNDVI .gdalinfo"          ../../Daniel_Zamorano/Rasters/Transf__promNDVI_.gdalinfo
# mv "../../Daniel_Zamorano/ClimaGeo_com/Transf_ asp_y .gdalinfo"        ../../Daniel_Zamorano/ClimaGeo_com/Transf__asp_y_.gdalinfo
# mv "../../Daniel_Zamorano/ClimaGeo_com/Transf_ TRI .gdalinfo"          ../../Daniel_Zamorano/ClimaGeo_com/Transf__TRI_.gdalinfo
# mv "../../Daniel_Zamorano/ClimaGeo_com/Transf_ slope .gdalinfo"        ../../Daniel_Zamorano/ClimaGeo_com/Transf__slope_.gdalinfo
# mv "../../Daniel_Zamorano/ClimaGeo_com/Transf_ asp_x .gdalinfo"        ../../Daniel_Zamorano/ClimaGeo_com/Transf__asp_x_.gdalinfo
# mv "../../Daniel_Zamorano/Vegetacion/Transf_ dNDVI .gdalinfo"          ../../Daniel_Zamorano/Vegetacion/Transf__dNDVI_.gdalinfo
# mv "../../Daniel_Zamorano/Vegetacion/Transf_ SOS .gdalinfo"            ../../Daniel_Zamorano/Vegetacion/Transf__SOS_.gdalinfo
# mv "../../Daniel_Zamorano/Vegetacion/Transf_ AMP .gdalinfo"            ../../Daniel_Zamorano/Vegetacion/Transf__AMP_.gdalinfo
# mv "../../Daniel_Zamorano/Vegetacion/Transf_ LOS .gdalinfo"            ../../Daniel_Zamorano/Vegetacion/Transf__LOS_.gdalinfo
# mv "../../Daniel_Zamorano/Vegetacion/Transf_ Carbono_2013 .gdalinfo"   ../../Daniel_Zamorano/Vegetacion/Transf__Carbono_2013_.gdalinfo
# mv "../../Daniel_Zamorano/Vegetacion/Transf_ EOS .gdalinfo"            ../../Daniel_Zamorano/Vegetacion/Transf__EOS_.gdalinfo
# mv "../../Daniel_Zamorano/Vegetacion/Transf_ promNDVI .gdalinfo"       ../../Daniel_Zamorano/Vegetacion/Transf__promNDVI_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ dNDVI .gdalinfo"               ../../Daniel_Zamorano/sobra/Transf__dNDVI_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ dNDVI_25 .gdalinfo"            ../../Daniel_Zamorano/sobra/Transf__dNDVI_25_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ SOS .gdalinfo"                 ../../Daniel_Zamorano/sobra/Transf__SOS_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ AMP .gdalinfo"                 ../../Daniel_Zamorano/sobra/Transf__AMP_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ bio_12 .gdalinfo"              ../../Daniel_Zamorano/sobra/Transf__bio_12_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ AMP_25 .gdalinfo"              ../../Daniel_Zamorano/sobra/Transf__AMP_25_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ LOS .gdalinfo"                 ../../Daniel_Zamorano/sobra/Transf__LOS_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ Carbono_2013 .gdalinfo"        ../../Daniel_Zamorano/sobra/Transf__Carbono_2013_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ Transf_ Dist_agua  .gdalinfo"  ../../Daniel_Zamorano/sobra/Transf__Transf__Dist_agua__.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ SOS_25 .gdalinfo"              ../../Daniel_Zamorano/sobra/Transf__SOS_25_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ asp_y .gdalinfo"               ../../Daniel_Zamorano/sobra/Transf__asp_y_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ EOS .gdalinfo"                 ../../Daniel_Zamorano/sobra/Transf__EOS_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ slope .gdalinfo"               ../../Daniel_Zamorano/sobra/Transf__slope_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ LOS_25 .gdalinfo"              ../../Daniel_Zamorano/sobra/Transf__LOS_25_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ bio_15 .gdalinfo"              ../../Daniel_Zamorano/sobra/Transf__bio_15_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ EOS_25 .gdalinfo"              ../../Daniel_Zamorano/sobra/Transf__EOS_25_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ asp_x .gdalinfo"               ../../Daniel_Zamorano/sobra/Transf__asp_x_.gdalinfo
# mv "../../Daniel_Zamorano/sobra/Transf_ promNDVI .gdalinfo"            ../../Daniel_Zamorano/sobra/Transf__promNDVI_.gdalinfo
# mv "../../Daniel_Zamorano/ClimaGeo/Transf_ bio_12 .gdalinfo"           ../../Daniel_Zamorano/ClimaGeo/Transf__bio_12_.gdalinfo
# mv "../../Daniel_Zamorano/ClimaGeo/Transf_ Dist_agua .gdalinfo"        ../../Daniel_Zamorano/ClimaGeo/Transf__Dist_agua_.gdalinfo
# mv "../../Daniel_Zamorano/ClimaGeo/Transf_ asp_y .gdalinfo"            ../../Daniel_Zamorano/ClimaGeo/Transf__asp_y_.gdalinfo
# mv "../../Daniel_Zamorano/ClimaGeo/Transf_ slope .gdalinfo"            ../../Daniel_Zamorano/ClimaGeo/Transf__slope_.gdalinfo
# mv "../../Daniel_Zamorano/ClimaGeo/Transf_ dem30_final .gdalinfo"      ../../Daniel_Zamorano/ClimaGeo/Transf__dem30_final_.gdalinfo
# mv "../../Daniel_Zamorano/ClimaGeo/Transf_ bio_15 .gdalinfo"           ../../Daniel_Zamorano/ClimaGeo/Transf__bio_15_.gdalinfo
# mv "../../Daniel_Zamorano/ClimaGeo/Transf_ asp_x .gdalinfo"            ../../Daniel_Zamorano/ClimaGeo/Transf__asp_x_.gdalinfo
