  source( "DefinirVariables.R" )
  setwd( bakdir )
  library( bigmemory )
  options(bigmemory.allow.dimnames=TRUE)
  grupo03_bigkmeans_kmn0007_grp03_var08_cluster <- bigmemory::attach.big.matrix( dget( "grupo03_bigkmeans_kmn0007_grp03_var08_cluster.desc" ) )
  colnames( grupo03_bigkmeans_kmn0007_grp03_var08_cluster ) <- c( "Eje__x_scaled","Eje__y_scaled","Asp__x_scaled","Asp__y_scaled","DEM_scaled","NDMI_scaled","Slope_scaled","TWI_scaled","Asp__x","Asp__y","DEM","NDMI","Slope","TWI","Cluster" )
  setwd( srcdir )
