  R --slave -f "RutinaMatConf_PlotPromedio_grupo00.R"
  R --slave -f "RutinaMatConf_PlotPromedio_grupo01.R"
  R --slave -f "RutinaMatConf_PlotPromedio_grupo02.R"
  R --slave -f "RutinaMatConf_PlotPromedio_grupo03.R"
  R --slave -f "RutinaMatConf_PlotPromedio_grupo04.R"
  R --slave -f "RutinaMatConf_PlotPromedio_grupo05.R"
  R --slave -f "RutinaMatConf_PlotPromedio_grupo06.R"
